POST http://localhost:8080/authenticate
Content-Type: application/x-www-form-urlencoded

user_name=admin&password=123456

> {% client.global.set("auth_token", response.body.data.token); %}

###
GET http://localhost:8080/current_user
Accept: application/json
Authorization: Bearer {{auth_token}}

###
POST http://localhost:8080/users/add_user
Content-Type: application/json
Authorization: Bearer {{auth_token}}
{
"user_name": "test",
"nick_name": "测试账号"
}

###
